package pl.cuyer.rusthub.presentation.ui

object Colors {
    const val PRIMARY_LIGHT = 0xFF3E6837
    const val ON_PRIMARY_LIGHT = 0xFFFFFFFF
    const val PRIMARY_CONTAINER_LIGHT = 0xFFBFF0B1
    const val ON_PRIMARY_CONTAINER_LIGHT = 0xFF275021
    const val SECONDARY_LIGHT = 0xFF53634E
    const val ON_SECONDARY_LIGHT = 0xFFFFFFFF
    const val SECONDARY_CONTAINER_LIGHT = 0xFFD6E8CD
    const val ON_SECONDARY_CONTAINER_LIGHT = 0xFF3C4B37
    const val TERTIARY_LIGHT = 0xFF386569
    const val ON_TERTIARY_LIGHT = 0xFFFFFFFF
    const val TERTIARY_CONTAINER_LIGHT = 0xFFBCEBEF
    const val ON_TERTIARY_CONTAINER_LIGHT = 0xFF1E4D51
    const val ERROR_LIGHT = 0xFFBA1A1A
    const val ON_ERROR_LIGHT = 0xFFFFFFFF
    const val ERROR_CONTAINER_LIGHT = 0xFFFFDAD6
    const val ON_ERROR_CONTAINER_LIGHT = 0xFF93000A
    const val BACKGROUND_LIGHT = 0xFFF8FBF1
    const val ON_BACKGROUND_LIGHT = 0xFF191D17
    const val SURFACE_LIGHT = 0xFFF8FBF1
    const val ON_SURFACE_LIGHT = 0xFF191D17
    const val SURFACE_VARIANT_LIGHT = 0xFFDFE4D8
    const val ON_SURFACE_VARIANT_LIGHT = 0xFF42493F
    const val OUTLINE_LIGHT = 0xFF73796E
    const val OUTLINE_VARIANT_LIGHT = 0xFFC2C8BC
    const val SCRIM_LIGHT = 0xFF000000
    const val INVERSE_SURFACE_LIGHT = 0xFF2E322B
    const val INVERSE_ON_SURFACE_LIGHT = 0xFFEFF2E8
    const val INVERSE_PRIMARY_LIGHT = 0xFFA4D397
    const val SURFACE_DIM_LIGHT = 0xFFD8DBD2
    const val SURFACE_BRIGHT_LIGHT = 0xFFF8FBF1
    const val SURFACE_CONTAINER_LOWEST_LIGHT = 0xFFFFFFFF
    const val SURFACE_CONTAINER_LOW_LIGHT = 0xFFF2F5EB
    const val SURFACE_CONTAINER_LIGHT = 0xFFECEFE5
    const val SURFACE_CONTAINER_HIGH_LIGHT = 0xFFE6E9E0
    const val SURFACE_CONTAINER_HIGHEST_LIGHT = 0xFFE0E4DA


    const val PRIMARY_DARK = 0xFFA4D397
    const val ON_PRIMARY_DARK = 0xFF0F380C
    const val PRIMARY_CONTAINER_DARK = 0xFF275021
    const val ON_PRIMARY_CONTAINER_DARK = 0xFFBFF0B1
    const val SECONDARY_DARK = 0xFFBBCCB2
    const val ON_SECONDARY_DARK = 0xFF263422
    const val SECONDARY_CONTAINER_DARK = 0xFF3C4B37
    const val ON_SECONDARY_CONTAINER_DARK = 0xFFD6E8CD
    const val TERTIARY_DARK = 0xFFA0CFD3
    const val ON_TERTIARY_DARK = 0xFF00363A
    const val TERTIARY_CONTAINER_DARK = 0xFF1E4D51
    const val ON_TERTIARY_CONTAINER_DARK = 0xFFBCEBEF
    const val ERROR_DARK = 0xFFFFB4AB
    const val ON_ERROR_DARK = 0xFF690005
    const val ERROR_CONTAINER_DARK = 0xFF93000A
    const val ON_ERROR_CONTAINER_DARK = 0xFFFFDAD6
    const val BACKGROUND_DARK = 0xFF11140F
    const val ON_BACKGROUND_DARK = 0xFFE0E4DA
    const val SURFACE_DARK = 0xFF11140F
    const val ON_SURFACE_DARK = 0xFFE0E4DA
    const val SURFACE_VARIANT_DARK = 0xFF42493F
    const val ON_SURFACE_VARIANT_DARK = 0xFFC2C8BC
    const val OUTLINE_DARK = 0xFF8C9387
    const val OUTLINE_VARIANT_DARK = 0xFF42493F
    const val SCRIM_DARK = 0xFF000000
    const val INVERSE_SURFACE_DARK = 0xFFE0E4DA
    const val INVERSE_ON_SURFACE_DARK = 0xFF2E322B
    const val INVERSE_PRIMARY_DARK = 0xFF3E6837
    const val SURFACE_DIM_DARK = 0xFF11140F
    const val SURFACE_BRIGHT_DARK = 0xFF363A34
    const val SURFACE_CONTAINER_LOWEST_DARK = 0xFF0B0F0A
    const val SURFACE_CONTAINER_LOW_DARK = 0xFF191D17
    const val SURFACE_CONTAINER_DARK = 0xFF1D211B
    const val SURFACE_CONTAINER_HIGH_DARK = 0xFF272B25
    const val SURFACE_CONTAINER_HIGHEST_DARK = 0xFF32362F

}