package pl.cuyer.rusthub.presentation.ui

object Colors {
    const val PRIMARY_LIGHT = 0xFFAB2915
    const val ON_PRIMARY_LIGHT = 0xFFFFFFFF
    const val PRIMARY_CONTAINER_LIGHT = 0xFFCE422B
    const val ON_PRIMARY_CONTAINER_LIGHT = 0xFFFFF9F8
    const val SECONDARY_LIGHT = 0xFF954839
    const val ON_SECONDARY_LIGHT = 0xFFFFFFFF
    const val SECONDARY_CONTAINER_LIGHT = 0xFFFE9C8A
    const val ON_SECONDARY_CONTAINER_LIGHT = 0xFF783125
    const val TERTIARY_LIGHT = 0xFF59601A
    const val ON_TERTIARY_LIGHT = 0xFFFFFFFF
    const val TERTIARY_CONTAINER_LIGHT = 0xFF727A31
    const val ON_TERTIARY_CONTAINER_LIGHT = 0xFFFEFFDB
    const val ERROR_LIGHT = 0xFFBA1A1A
    const val ON_ERROR_LIGHT = 0xFFFFFFFF
    const val ERROR_CONTAINER_LIGHT = 0xFFFFDAD6
    const val ON_ERROR_CONTAINER_LIGHT = 0xFF93000A
    const val BACKGROUND_LIGHT = 0xFFFFF8F6
    const val ON_BACKGROUND_LIGHT = 0xFF261816
    const val SURFACE_LIGHT = 0xFFFFF8F6
    const val ON_SURFACE_LIGHT = 0xFF261816
    const val SURFACE_VARIANT_LIGHT = 0xFFFFDAD3
    const val ON_SURFACE_VARIANT_LIGHT = 0xFF5A413C
    const val OUTLINE_LIGHT = 0xFF8D706B
    const val OUTLINE_VARIANT_LIGHT = 0xFFE2BFB8
    const val SCRIM_LIGHT = 0xFF000000
    const val INVERSE_SURFACE_LIGHT = 0xFF3C2D2A
    const val INVERSE_ON_SURFACE_LIGHT = 0xFFFFEDE9
    const val INVERSE_PRIMARY_LIGHT = 0xFFFFB4A6
    const val SURFACE_DIM_LIGHT = 0xFFEED4D0
    const val SURFACE_BRIGHT_LIGHT = 0xFFFFF8F6
    const val SURFACE_CONTAINER_LOWEST_LIGHT = 0xFFFFFFFF
    const val SURFACE_CONTAINER_LOW_LIGHT = 0xFFFFF0EE
    const val SURFACE_CONTAINER_LIGHT = 0xFFFFE9E5
    const val SURFACE_CONTAINER_HIGH_LIGHT = 0xFFFDE2DD
    const val SURFACE_CONTAINER_HIGHEST_LIGHT = 0xFFF7DDD8


    const val PRIMARY_DARK = 0xFFFFB4A6
    const val ON_PRIMARY_DARK = 0xFF660800
    const val PRIMARY_CONTAINER_DARK = 0xFFCE422B
    const val ON_PRIMARY_CONTAINER_DARK = 0xFFFFF9F8
    const val SECONDARY_DARK = 0xFFFFB4A6
    const val ON_SECONDARY_DARK = 0xFF5A1B11
    const val SECONDARY_CONTAINER_DARK = 0xFF773124
    const val ON_SECONDARY_CONTAINER_DARK = 0xFFFD9B89
    const val TERTIARY_DARK = 0xFFC4CD7A
    const val ON_TERTIARY_DARK = 0xFF2E3300
    const val TERTIARY_CONTAINER_DARK = 0xFF8E964A
    const val ON_TERTIARY_CONTAINER_DARK = 0xFF282C00
    const val ERROR_DARK = 0xFFFFB4AB
    const val ON_ERROR_DARK = 0xFF690005
    const val ERROR_CONTAINER_DARK = 0xFF93000A
    const val ON_ERROR_CONTAINER_DARK = 0xFFFFDAD6
    const val BACKGROUND_DARK = 0xFF1D100E
    const val ON_BACKGROUND_DARK = 0xFFF7DDD8
    const val SURFACE_DARK = 0xFF1D100E
    const val ON_SURFACE_DARK = 0xFFF7DDD8
    const val SURFACE_VARIANT_DARK = 0xFF5A413C
    const val ON_SURFACE_VARIANT_DARK = 0xFFE2BFB8
    const val OUTLINE_DARK = 0xFFA98A84
    const val OUTLINE_VARIANT_DARK = 0xFF5A413C
    const val SCRIM_DARK = 0xFF000000
    const val INVERSE_SURFACE_DARK = 0xFFF7DDD8
    const val INVERSE_ON_SURFACE_DARK = 0xFF3C2D2A
    const val INVERSE_PRIMARY_DARK = 0xFFB12D18
    const val SURFACE_DIM_DARK = 0xFF1D100E
    const val SURFACE_BRIGHT_DARK = 0xFF463532
    const val SURFACE_CONTAINER_LOWEST_DARK = 0xFF170B09
    const val SURFACE_CONTAINER_LOW_DARK = 0xFF261816
    const val SURFACE_CONTAINER_DARK = 0xFF2A1C19
    const val SURFACE_CONTAINER_HIGH_DARK = 0xFF362623
    const val SURFACE_CONTAINER_HIGHEST_DARK = 0xFF41312E

}