package pl.cuyer.rusthub.presentation.ui

object Colors {
    const val PRIMARY_LIGHT = 0xFF006E22
    const val ON_PRIMARY_LIGHT = 0xFFFFFFFF
    const val PRIMARY_CONTAINER_LIGHT = 0xFF37F963
    const val ON_PRIMARY_CONTAINER_LIGHT = 0xFF006E23

    const val SECONDARY_LIGHT = 0xFF056E23
    const val ON_SECONDARY_LIGHT = 0xFFFFFFFF
    const val SECONDARY_CONTAINER_LIGHT = 0xFF9BF89B
    const val ON_SECONDARY_CONTAINER_LIGHT = 0xFF127429

    const val TERTIARY_LIGHT = 0xFF00696B
    const val ON_TERTIARY_LIGHT = 0xFFFFFFFF
    const val TERTIARY_CONTAINER_LIGHT = 0xFF00F1F4
    const val ON_TERTIARY_CONTAINER_LIGHT = 0xFF006A6B

    const val ERROR_LIGHT = 0xFFBA1A1A
    const val ON_ERROR_LIGHT = 0xFFFFFFFF
    const val ERROR_CONTAINER_LIGHT = 0xFFFFDAD6
    const val ON_ERROR_CONTAINER_LIGHT = 0xFF93000A

    const val BACKGROUND_LIGHT = 0xFFF2FDEC
    const val ON_BACKGROUND_LIGHT = 0xFF151E14
    const val SURFACE_LIGHT = 0xFFF2FDEC
    const val ON_SURFACE_LIGHT = 0xFF151E14
    const val SURFACE_VARIANT_LIGHT = 0xFFD6E7D1
    const val ON_SURFACE_VARIANT_LIGHT = 0xFF3C4B3A

    const val OUTLINE_LIGHT = 0xFF6B7B68
    const val OUTLINE_VARIANT_LIGHT = 0xFFBACBB5
    const val SCRIM_LIGHT = 0xFF000000

    const val INVERSE_SURFACE_LIGHT = 0xFF293328
    const val INVERSE_ON_SURFACE_LIGHT = 0xFFE9F4E3
    const val INVERSE_PRIMARY_LIGHT = 0xFF04E552

    const val SURFACE_DIM_LIGHT = 0xFFD2DDCD
    const val SURFACE_BRIGHT_LIGHT = 0xFFF2FDEC

    const val SURFACE_CONTAINER_LOWEST_LIGHT = 0xFFFFFFFF
    const val SURFACE_CONTAINER_LOW_LIGHT = 0xFFECF7E6
    const val SURFACE_CONTAINER_LIGHT = 0xFFE6F1E0
    const val SURFACE_CONTAINER_HIGH_LIGHT = 0xFFE0EBDB
    const val SURFACE_CONTAINER_HIGHEST_LIGHT = 0xFFDBE6D5

    const val PRIMARY_DARK = 0xFFDDFFD7
    const val ON_PRIMARY_DARK = 0xFF00390E
    const val PRIMARY_CONTAINER_DARK = 0xFF37F963
    const val ON_PRIMARY_CONTAINER_DARK = 0xFF006E23

    const val SECONDARY_DARK = 0xFF7FDB82
    const val ON_SECONDARY_DARK = 0xFF00390E
    const val SECONDARY_CONTAINER_DARK = 0xFF006B21
    const val ON_SECONDARY_CONTAINER_DARK = 0xFF8DEA8F

    const val TERTIARY_DARK = 0xFFCEFFFF
    const val ON_TERTIARY_DARK = 0xFF003738
    const val TERTIARY_CONTAINER_DARK = 0xFF00F1F4
    const val ON_TERTIARY_CONTAINER_DARK = 0xFF006A6B

    const val ERROR_DARK = 0xFFFFB4AB
    const val ON_ERROR_DARK = 0xFF690005
    const val ERROR_CONTAINER_DARK = 0xFF93000A
    const val ON_ERROR_CONTAINER_DARK = 0xFFFFDAD6

    const val BACKGROUND_DARK = 0xFF0D160C
    const val ON_BACKGROUND_DARK = 0xFFDBE6D5
    const val SURFACE_DARK = 0xFF0D160C
    const val ON_SURFACE_DARK = 0xFFDBE6D5
    const val SURFACE_VARIANT_DARK = 0xFF3C4B3A
    const val ON_SURFACE_VARIANT_DARK = 0xFFBACBB5

    const val OUTLINE_DARK = 0xFF859581
    const val OUTLINE_VARIANT_DARK = 0xFF3C4B3A
    const val SCRIM_DARK = 0xFF000000

    const val INVERSE_SURFACE_DARK = 0xFFDBE6D5
    const val INVERSE_ON_SURFACE_DARK = 0xFF293328
    const val INVERSE_PRIMARY_DARK = 0xFF006E22

    const val SURFACE_DIM_DARK = 0xFF0D160C
    const val SURFACE_BRIGHT_DARK = 0xFF323C30

    const val SURFACE_CONTAINER_LOWEST_DARK = 0xFF081007
    const val SURFACE_CONTAINER_LOW_DARK = 0xFF151E14
    const val SURFACE_CONTAINER_DARK = 0xFF192218
    const val SURFACE_CONTAINER_HIGH_DARK = 0xFF232C22
    const val SURFACE_CONTAINER_HIGHEST_DARK = 0xFF2E372C1

}